name: Chip-8
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make Makefile.libretro -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          ./
